# Generated by Django 5.2.13 on 2026-05-07 13:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_annual_interest_amount_loan_monthly_payment_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='payment_schedule',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_schedule',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='due_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.paymentschedule'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='interest_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='month_number',
            field=models.PositiveIntegerField(blank=True, help_text='1 = January ... 12 = December', null=True),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loan.loan'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='months_missed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penalty',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes from bank staff', null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount due before penalty', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='5% of the original amount due', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='penalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('5.00'), help_text='Penalty rate as percentage — default is 5%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount + penalty amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], default='cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('late_payment', 'Late Payment — 5% added'), ('collateral_seizure', 'Collateral Seizure — 2 months missed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('seized', 'Collateral Seized')], default='active', max_length=20),
        ),
    ]
