# Generated by Django 5.2.13 on 2026-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_method_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('linked_bank_account', 'Linked Bank Account'), ('debit_credit_card', 'Debit / Credit Card'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20, null=True),
        ),
    ]
