# Generated by Django 5.2.13 on 2026-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('social', 'Social Loan'), ('construction', 'Construction Loan'), ('commercial', 'Commercial Loan'), ('salary', 'Salary Loan'), ('ibimina', 'Ibimina Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collateral_type', models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('collateral_description', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
