# Generated by Django 5.2.13 on 2026-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='annual_interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Interest amount per year (amount x interest_rate / 100)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Fixed monthly payment amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total amount to repay (principal + total interest)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(choices=[('17.00', '17% per year'), ('18.00', '18% per year'), ('19.00', '19% per year')], decimal_places=2, default='17.00', help_text='Annual interest rate set by the bank (17% - 19%)', max_digits=5),
        ),
    ]
