# Generated by Django 5.2.13 on 2026-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_annual_interest_amount_loan_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='collateral_type',
            field=models.CharField(choices=[('LAND', 'LAND'), ('HOUSE', 'HOUSE'), ('CAR', 'CAR'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[(' SOCIAL', 'SOCIAL LOAN'), ('CONSTRUCTION', 'CONSTRACTION LOAN'), ('COMMERCIAL', 'Commercial Loan'), ('SALARY', 'SALARY LOAN'), ('IBIMINA', 'IBIMINA LOAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
