# Generated by Django 5.2.13 on 2026-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_collateral_type_alter_loan_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('SOCIAL', 'SOCIAL LOAN'), ('CONSTRUCTION', 'CONSTRACTION LOAN'), ('COMMERCIAL', 'Commercial Loan'), ('SALARY', 'SALARY LOAN'), ('IBIMINA', 'IBIMINA LOAN')], max_length=20),
        ),
    ]
