# Generated by Django 5.2.13

import loanapplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='national_id',
            field=models.FileField(
                help_text='National ID or passport of applicant (and guarantor for salary loan) — PDF, JPG or PNG, max 5MB',
                upload_to='documents/national_id/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='civil_status_cert',
            field=models.FileField(
                help_text='Civil status certificate (marriage/single/etc) — PDF, JPG or PNG, max 5MB',
                upload_to='documents/civil_status_cert/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='guarantor_id',
            field=models.FileField(
                blank=True, null=True,
                help_text='Guarantor national ID — required for Construction and Social loans',
                upload_to='documents/guarantor_id/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='collateral_doc',
            field=models.FileField(
                blank=True, null=True,
                help_text='Collateral document — required for Construction and Social loans',
                upload_to='documents/collateral_doc/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='property_valuation',
            field=models.FileField(
                blank=True, null=True,
                help_text='Property valuation document — PDF, JPG or PNG, max 5MB',
                upload_to='documents/property_valuation/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='building_permit',
            field=models.FileField(
                blank=True, null=True,
                help_text='Building permit — PDF, JPG or PNG, max 5MB',
                upload_to='documents/building_permit/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='payslips',
            field=models.FileField(
                blank=True, null=True,
                help_text='Last 3 months payslips — PDF, JPG or PNG, max 5MB',
                upload_to='documents/payslips/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='employment_letter',
            field=models.FileField(
                blank=True, null=True,
                help_text='Employment confirmation letter — PDF, JPG or PNG, max 5MB',
                upload_to='documents/employment_letter/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='ibimina_certificate',
            field=models.FileField(
                blank=True, null=True,
                help_text='Ibimina group registration certificate — PDF, JPG or PNG, max 5MB',
                upload_to='documents/ibimina_certificate/',
                validators=[loanapplication.models.validate_document],
            ),
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='business_plan',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='trading_license',
        ),
    ]
